- packages/gi-cli/.fatherrc.ts
- packages/gi-cli/.gitignore
- packages/gi-cli/README.md
- packages/gi-cli/bin/gi-create.js
- packages/gi-cli/package.json
- packages/gi-cli/src/cli.ts
- packages/gi-cli/templates/.gitignore
- packages/gi-cli/templates/.umirc.ts
- packages/gi-cli/templates/README.md
- packages/gi-cli/templates/components/Counter/Component.tsx
- packages/gi-cli/templates/components/Counter/index.tsx
- packages/gi-cli/templates/components/Counter/info.ts
- packages/gi-cli/templates/components/Counter/registerMeta.ts
- packages/gi-cli/templates/components/index.ts
- packages/gi-cli/templates/elements/ClusterNode/index.md
- packages/gi-cli/templates/elements/ClusterNode/index.tsx
- packages/gi-cli/templates/elements/ClusterNode/registerMeta.tsx
- packages/gi-cli/templates/elements/ClusterNode/registerShape.ts
- packages/gi-cli/templates/elements/ClusterNode/registerTransform.ts
- packages/gi-cli/templates/elements/index.ts
- packages/gi-cli/templates/package.json.tpl
- packages/gi-cli/templates/pages/GI_EXPORT_FILES.ts
- packages/gi-cli/templates/pages/index.tsx
- packages/gi-cli/templates/pages/utils.ts
- packages/gi-cli/tsconfig.json
- pnpm-lock.yaml
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
Add the create CLi tool for GraphInsight assets
> feat: add the gi-cli package

- packages/gi-assets-advance/src/components/ModeSwitch/Component.tsx
- packages/gi-assets-algorithm/src/PatternMatch/index.less
- packages/gi-assets-algorithm/src/PatternMatch/patternEditor.tsx
fix: pattern match error while opening the config drawer
> fix: pattern match error while opening the config drawer

- packages/gi-assets-graphscope/src/services/ServerComponent/index.less
- packages/gi-site/src/components/FileServerEngine/UploadLocalFile.tsx
- packages/gi-site/src/components/FileServerEngine/index.less
- packages/gi-site/src/components/FileServerEngine/utils.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
add download example mock data
> feat: add download example mock data

- package.json
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> fix: 修复打包指令

- packages/gi-sdk/src/process/serverEngineContext.ts
- packages/gi-site/src/pages/Analysis/MetaPanel/DataPanel/index.tsx
- packages/gi-site/src/services/index.ts
- packages/gi-site/src/services/user.ts
- packages/gi-site/src/services/utils.ts
> feat: 更新服务接口

- packages/gi-assets-basic/src/components/ActivateRelations/ActiveEdge.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> fix: edge selection state

- packages/gi-assets-basic/src/components/GrailLayout/Component.tsx
- packages/gi-assets-basic/src/components/GrailLayout/registerMeta.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
Solve the issue and close #56
> feat: 增加圣杯布局容器默认展开配置

- packages/gi-assets-neo4j/src/services/CypherQuery.ts
- packages/gi-assets-neo4j/src/services/Initializer.ts
- packages/gi-assets-neo4j/src/services/NeighborsQuery.ts
- packages/gi-assets-neo4j/src/services/Neo4jService.ts
- packages/gi-site/src/hooks/common.ts
- pnpm-lock.yaml
✨ Feature
🎨 Enhance
🐛 Bugfix
- fix #68 
🔧 Chore
> fix: neo4j  in exported html not work

- packages/gi-assets-basic/package.json
- packages/gi-assets-neo4j/package.json
- packages/gi-site/package.json
- packages/gi-site/src/services/const.tsx
> chore: 发布站点 1.2.0

- packages/gi-site/src/hooks/common.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- fix #76
> fix: cdn graphin css miss

- packages/gi-sdk/src/typing.ts
- packages/gi-site/src/pages/Analysis/index.tsx
- packages/gi-site/src/pages/Analysis/utils.tsx
- packages/gi-site/src/services/const.tsx
> feat: 增加引擎模版

- packages/gi-assets-basic/src/components/FilterPanel/FilterSelection.tsx
> feat: filter panel searchable

- packages/gi-site/src/pages/Assets/Upload.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> fix: upload placeholder

- packages/gi-site/src/services/index.md
> feat: add api docs

- packages/gi-assets-basic/src/components/ZoomStatus/Component.tsx
- packages/gi-assets-basic/src/components/ZoomStatus/index.md
- packages/gi-assets-basic/src/components/ZoomStatus/index.tsx
- packages/gi-assets-basic/src/components/ZoomStatus/info.ts
- packages/gi-assets-basic/src/components/ZoomStatus/registerMeta.ts
- packages/gi-assets-basic/src/components/index.tsx
- packages/gi-assets-basic/src/elements/SimpleEdge/registerTransform.ts
- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
✨ Feature
Add ZoomStatus Assets
Add the status when the zoom is less than the specified value
> add zoomStatus assets

- packages/gi-assets-basic/src/components/ZoomStatus/Component.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
fix:clear task before component unmount
> fix:clear task before component unmount

- packages/gi-site/docker/Makefile
- packages/gi-site/docker/website.Dockerfile
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> Containerized deployment for graphinsight website

- packages/gi-assets-basic/src/elements/SimpleEdge/registerMeta.tsx
- packages/gi-assets-basic/src/elements/SimpleEdge/registerTransform.ts
> feat: 开放箭头配置

- packages/gi-assets-advance/src/components/Redo/Component.tsx
- packages/gi-assets-advance/src/components/Redo/index.tsx
- packages/gi-assets-advance/src/components/Redo/info.ts
- packages/gi-assets-advance/src/components/Redo/registerMeta.ts
- packages/gi-assets-advance/src/components/Undo/Component.tsx
- packages/gi-assets-advance/src/components/Undo/index.tsx
- packages/gi-assets-advance/src/components/Undo/info.ts
- packages/gi-assets-advance/src/components/Undo/registerMeta.ts
- packages/gi-assets-advance/src/components/hooks/useRedoUndo.tsx
- packages/gi-assets-advance/src/components/index.tsx
- packages/gi-assets-basic/src/components/ZoomStatus/Component.tsx
- packages/gi-assets-basic/src/components/ZoomStatus/index.md
- packages/gi-assets-basic/src/components/ZoomStatus/index.tsx
- packages/gi-assets-basic/src/components/ZoomStatus/info.ts
- packages/gi-assets-basic/src/components/ZoomStatus/registerMeta.ts
- packages/gi-assets-basic/src/components/index.tsx
- packages/gi-assets-basic/src/elements/SimpleEdge/registerTransform.ts
- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
some nodes lose position information before pushed into the stack
> Kongtan fix redo undo

- packages/gi-assets-basic/src/components/SideTabs/Component.tsx
- packages/gi-assets-basic/src/components/SideTabs/registerMeta.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
侧边栏添加默认展开配置，有些场景默认不需要展开侧边栏
> feat: 支持侧边栏的默认展开配置

- packages/gi-assets-basic/src/components/FilterPanel/Component.tsx
- packages/gi-site/src/components/Navbar/ExportConfig.tsx
- packages/gi-site/src/components/Navbar/index.tsx
- packages/gi-site/src/components/ProjectCard/index.less
- packages/gi-site/src/components/ProjectCard/index.tsx
- packages/gi-site/src/hooks/common.ts
- packages/gi-site/src/hooks/useCodeSandbox.ts
- packages/gi-site/src/hooks/useHtml.ts
- packages/gi-site/src/hooks/useNodeModule.ts
- packages/gi-site/src/pages/Workspace/Projects.tsx
- packages/gi-site/src/pages/Workspace/SaveList.tsx
- packages/gi-site/src/pages/Workspace/utils.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> chore: export sdk on project page

- packages/gi-common-components/src/RadiusTabs/index.less
- packages/gi-site/public/css/gi-theme-antd.ali.css
- packages/gi-site/public/css/gi-theme-antd.dark.css
- packages/gi-site/src/components/DataModeCard/index.less
- packages/gi-site/src/components/DataSource/index.less
- packages/gi-site/src/components/Navbar/BaseNavbar.tsx
- packages/gi-site/src/components/Navbar/Basic.tsx
- packages/gi-site/src/components/Navbar/index.less
- packages/gi-site/src/components/ProjectCard/index.less
- packages/gi-site/src/components/RadioNote/index.less
- packages/gi-site/src/components/SegmentedTabs/index.tsx
- packages/gi-site/src/components/ThemeVars/index.ts
- packages/gi-site/src/components/ThemeVars/useTheme.tsx
- packages/gi-site/src/layouts/SideNav.tsx
- packages/gi-site/src/layouts/index.less
- packages/gi-site/src/pages/Analysis/MetaPanel/StylesPanel/index.less
- packages/gi-site/src/pages/Dataset/Create.tsx
- packages/gi-site/src/pages/Dataset/Detail.tsx
- packages/gi-site/src/pages/Dataset/List.tsx
- packages/gi-site/src/pages/Home/GuideCards.tsx
- packages/gi-site/src/pages/Home/Notification.tsx
- packages/gi-site/src/pages/Home/index.less
- packages/gi-site/src/pages/Home/index.tsx
- packages/gi-site/src/pages/Workspace/index.less
- packages/gi-site/src/services/const.tsx
- packages/gi-theme-antd/package.json
- packages/gi-theme-antd/src/components/const.ts
- packages/gi-theme-antd/src/components/index.tsx
- packages/gi-theme-antd/src/theme/ali.js
- packages/gi-theme-antd/src/theme/config.js
> feat: theme styles for v2

- packages/gi-httpservice/app/controller/dataset.ts
- packages/gi-httpservice/app/router.ts
- packages/gi-httpservice/app/service/graphinsight/dataset.ts
- packages/gi-site/.umirc.ts
- packages/gi-site/src/components/ProjectCard/index.less
- packages/gi-site/src/components/ProjectCard/index.tsx
- packages/gi-site/src/components/ThemeVars/index.ts
- packages/gi-site/src/pages/Dataset/Case.tsx
- packages/gi-site/src/pages/Dataset/Delete.tsx
- packages/gi-site/src/pages/Dataset/List.tsx
- packages/gi-site/src/pages/Dataset/Table.tsx
- packages/gi-site/src/pages/Workspace/Projects.tsx
- packages/gi-site/src/services/dataset.tsx
- packages/gi-site/src/services/project.ts
- packages/gi-site/src/services/typing.ts
- packages/gi-theme-antd/src/components/const.ts
feat: dataset recycle and recovery
> feat: dataset recycle and recovery

- packages/gi-site/src/services/const.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> Fixes get service url in online env

- packages/gi-assets-advance/package.json
- packages/gi-assets-advance/src/components/JSONMode/Component.tsx
- packages/gi-assets-advance/src/components/JSONMode/index.less
- packages/gi-assets-advance/src/components/JSONMode/index.tsx
- packages/gi-assets-advance/src/components/JSONMode/info.ts
- packages/gi-assets-advance/src/components/JSONMode/registerMeta.ts
- packages/gi-assets-advance/src/components/index.tsx
- packages/gi-assets-basic/src/components/UadLayout/component.tsx
- packages/gi-assets-graphscope/src/components/ServerComponent/LoadGraph.tsx
- packages/gi-assets-graphscope/src/components/ServerComponent/utils.ts
- packages/gi-common-components/src/CommonStyleSetting/IconPicker/index.tsx
- packages/gi-httpservice/app/service/graphcompute.ts
- packages/gi-httpservice/app/service/graphscope.ts
- packages/gi-sdk/src/GISDK.tsx
- packages/gi-site/scripts/deps.json
- packages/gi-site/scripts/deps_externals.json
feat: 代码模式资产; 
fix: gremlin 查询报错时应停止 loading 并抛出报错信息;
> feat: 代码模式资产; fix: gremlin 查询报错时应停止 loading 并抛出报错信息;

- packages/gi-httpservice/app/service/graphscope.ts
> fix: gs gremlin 客户端清理

- packages/gi-assets-graphscope/src/services/ElementProperties.ts
- packages/gi-assets-graphscope/src/services/NeighborsQuery.ts
- packages/gi-httpservice/app/service/graphscope.ts
fix: graphscope neighbor query and property query problems
> fix: graphscope neighbor query and property query problems

- packages/gi-assets-basic/src/components/CommonNeighbor/Component.tsx
- packages/gi-assets-basic/src/components/CommonNeighbor/index.tsx
- packages/gi-assets-basic/src/components/CommonNeighbor/info.ts
- packages/gi-assets-basic/src/components/CommonNeighbor/registerMeta.ts
- packages/gi-assets-basic/src/components/ContextMenu/ContextMenu.tsx
- packages/gi-assets-basic/src/components/index.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
新增共同邻居资产: 高亮展示选中节点的共同邻居
> feat: add common neighbor

- .gitignore
- package.json
- pnpm-lock.yaml
- turbo.json
> feat: add turbo improve build speed

- packages/gi-httpservice/app/service/graphscope.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> Support gremlin query on multiple graph

- packages/gi-httpservice/app/service/graphcompute.ts
- packages/gi-httpservice/app/service/graphscope.ts
fix: gremlin query with valueMap
> fix: gremlin query with valueMap

- packages/gi-assets-advance/src/components/GraphAnnotation/Component.tsx
- packages/gi-assets-advance/src/components/GraphAnnotation/index.less
- packages/gi-assets-advance/src/components/GraphAnnotation/registerMeta.ts
- packages/gi-assets-advance/src/components/JSONMode/Component.tsx
- packages/gi-assets-advance/src/services/StyleSetting.ts
- packages/gi-assets-basic/src/components/ContentContainer/Component.tsx
- packages/gi-assets-basic/src/components/NeighborsQuery/Component.tsx
- packages/gi-assets-basic/src/components/SideTabs/Component.tsx
- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
- packages/gi-common-components/src/CommonStyleSetting/IconPicker/IconContent.tsx
- packages/gi-common-components/src/FilterPanel/FilterSelection.tsx
- packages/gi-common-components/src/FormilyForm/AssetCollapse/index.tsx
- packages/gi-common-components/src/FormilyForm/FormCollapse/usePrefixCls.ts
- packages/gi-common-components/src/SchemaField/index.tsx
feat: tag node with node annotation
> feat: tag node with node annotation

- packages/gi-assets-basic/src/components/SegmentedLayout/SegmentedTabs.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/component.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/index.less
- packages/gi-assets-basic/src/components/SegmentedLayout/index.ts
- packages/gi-assets-basic/src/components/SegmentedLayout/info.ts
- packages/gi-assets-basic/src/components/SegmentedLayout/registerMeta.ts
- packages/gi-assets-basic/src/components/SegmentedLayout/useComponents.tsx
- packages/gi-assets-basic/src/components/index.tsx
- packages/gi-site/src/components/Navbar/WorkbookNav.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsCenter.tsx
- packages/gi-site/src/pages/Analysis/index.tsx
> Pomelo.workbook

- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-algorithm/src/ClusterTable/index.tsx
- packages/gi-assets-algorithm/src/CommunityDetection/Component.tsx
- packages/gi-assets-algorithm/src/NodesClustering/Component.tsx
- packages/gi-assets-algorithm/src/NodesClustering/index.less
- packages/gi-assets-algorithm/src/NodesSimilarity/Component.tsx
- packages/gi-assets-basic/package.json
- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/FilterRule.tsx
- pnpm-lock.yaml
fix: algorithm analysis component problems
fix: path analyse component with endless loop
> fix: algorithm analysis component problems

- packages/gi-assets-advance/src/components/hooks/useRedoUndo.tsx
- packages/gi-assets-hugegraph/package.json
- packages/gi-site/scripts/assets_package.json
- packages/gi-site/src/services/assets.ts
fix: hugegraph version for workbook downloading
> fix: hugegraph version for workbook downloading

- packages/gi-assets-advance/src/components/ModeSwitch/Component.tsx
- packages/gi-assets-advance/src/components/ModeSwitch/registerMeta.ts
- packages/gi-assets-basic/src/components/OperatorBar/Component.tsx
- packages/gi-assets-basic/src/components/OperatorBar/index.less
- packages/gi-assets-basic/src/components/OperatorBar/registerMeta.ts
- packages/gi-assets-basic/src/components/SegmentedLayout/component.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/useComponents.tsx
- packages/gi-sdk/src/hooks/useComponents.tsx
- packages/gi-sdk/src/process/schema.ts
- packages/gi-site/src/components/AssetsCenter/index.less
- packages/gi-site/src/components/Navbar/SaveWorkbook.tsx
- packages/gi-site/src/components/Navbar/SiteNav.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/ComponentPanel.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/index.less
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsCenter.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/constants.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.less
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/index.less
- packages/gi-site/src/pages/Analysis/MetaPanel/index.tsx
- packages/gi-site/src/pages/Analysis/index.tsx
- packages/gi-site/src/services/initial.data/getConfigByEngineId.ts
- pnpm-lock.yaml
fix: 模式切换和操作栏的配置不起作用; 
fix: 配置面板中的资产集成与画布不一致问题;
chore: 工作簿存储与读取页面布局统一使用 context config pageLayout;
perf: 资产中心样式调整;
perf: 容器配置增加引导。
> fix: 配置面板中的资产集成与画布不一致问题

- packages/gi-assets-basic/src/components/GrailLayout/useComponents.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.tsx
- packages/gi-site/src/pages/Workbook/Create.tsx
- pnpm-lock.yaml
feat: recover project; fix: page layout config problem;
> feat: recover project; fix: page layout config problem;

- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/ComponentPanel.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.tsx
- packages/gi-site/src/pages/Analysis/index.tsx
fix: 旧版工作簿缓存信息中未存储 pageLayout，通过 components 恢复
> fix: 旧版工作簿缓存信息中未存储 pageLayout，通过 components 恢复

- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- 路径分析 输入框聚焦时点选节点自动填充
- 激活选择状态时文案提示
> feat: 聚焦时可点选节点

- packages/gi-site/README.md
> docs: Update Readme add FAQ

- packages/gi-cli/package.json
- packages/gi-cli/templates/src/pages/update.ts
- packages/gi-cli/templates/webpack.config.js
脚手架生成的模版代码有缺少组件 type 字段，会导致类型错误，无法正常 build
修复之后可以发个包
> fix: fix template issues that cause build error

- packages/gi-theme-antd/src/components/index.tsx
> feat: set data-theme when change theme

- package.json
- packages/gi-site/src/components/AssetsCenter/AssetsCenterHandler.tsx
- packages/gi-site/src/components/AssetsCenter/index.less
- packages/gi-site/src/services/assets.ts
fix: elements from all assets
fix: layouts from all assets
> fix: elements from all assets

- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
fix: path analysis with path unfound
> fix: path analysis with path unfound

- packages/gi-assets-basic/src/components/common/handlePinNode.tsx
- packages/gi-assets-basic/src/layouts/Force2/registerMeta.tsx
- packages/gi-sdk/src/GISDK.tsx
- packages/gi-site/src/components/Navbar/SaveWorkbook.tsx
fix: save workbook after configuring layout
> fix: save workbook after configuring layout

- packages/gi-assets-advance/src/components/Assistant/Component.tsx
- packages/gi-assets-advance/src/components/Assistant/Header/index.less
- packages/gi-assets-advance/src/components/Assistant/registerMeta.ts
* 提示词调整
* 局部样式调整
* 暂不对代码块做严格过滤
> fix: fix some problems of assistant

- packages/gi-common-components/src/Icon/index.tsx
- packages/gi-site/scripts/create-assets.mjs
- packages/gi-site/src/components/AssetsCenter/Card.tsx
- packages/gi-site/src/components/AssetsCenter/index.less
- packages/gi-site/src/components/Sidebar/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsCenter.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/RenderForm.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.less
- packages/gi-site/src/pages/Workspace/Projects.tsx
* 工作簿按照创建时间降序排序
* 更新 iconfont 配置
* 调整分类筛选逻辑 （取消最后一个选项后置为全选）
Before:
After:
* 资产选择器样式调整
Before:
After:
> refactor: adjustment for some details

- packages/gi-assets-advance/src/components/TableMode/Component.tsx
- packages/gi-assets-advance/src/components/TableMode/registerMeta.ts
- 增加 exportable 配置项 支持TableMode 导出 csv
> feat: exportable TableMode

- packages/gi-sdk/src/GISDK.tsx
- packages/gi-sdk/src/hooks/useComponents.tsx
- 修复 pageLayout 渲染时机问题，确保在 graph 实例之后渲染 pageLayout
> fix: pageLayout 渲染时机问题

- packages/gi-cli/package.json
- packages/gi-cli/templates/package.json.tpl
- packages/gi-cli/templates/src/components/MyLayout/Component.tsx
- packages/gi-cli/templates/src/components/MyLayout/index.tsx
- packages/gi-cli/templates/src/components/MyLayout/info.ts
- packages/gi-cli/templates/src/components/MyLayout/registerMeta.ts
- packages/gi-cli/templates/src/components/index.ts
- packages/gi-cli/templates/src/pages/GI_EXPORT_FILES.ts
- packages/gi-cli/templates/src/pages/ServerView.tsx
- packages/gi-cli/templates/src/pages/index.tsx
- packages/gi-cli/templates/src/pages/update.ts
> chore：update gi-cli

- packages/gi-httpservice/app/service/graphscope.ts
- packages/gi-httpservice/package.json
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> Unified the queryNodeProperties into queryElementProperties

- packages/gi-sdk/src/GISDK.tsx
> chore: 去除 debugger

- packages/gi-common-components/src/CommonStyleSetting/FormilyRenderForm.tsx
- packages/gi-common-components/src/SchemaField/index.tsx
RT: 目前组件配置无法使用 DatePicker
@pomelo-nwu  帮忙确认下是否变更这两处就可以了
> refactor: formily 表单增加 DatePicker 渲染

- packages/gi-assets-advance/src/components/AnalysisHistory/FlowGraph.tsx
- packages/gi-assets-advance/src/components/AnalysisHistory/flowNodeRegistry.tsx
- packages/gi-assets-advance/src/components/AnalysisHistory/type.tsx
- packages/gi-assets-advance/src/components/AnalysisHistory/util.tsx
> fix: 历史沉淀资产节点类型不正确

- packages/gi-assets-advance/src/components/TableMode/Component.tsx
> fix: 导出时 s2 实例丢失问题

- packages/gi-assets-advance/src/components/ThemeSetting/mockServices.ts
- packages/gi-site/public/css/gi-theme-antd.green.css
- packages/gi-site/src/components/Navbar/Theme.tsx
- packages/gi-site/src/components/Navbar/WorkbookNav.tsx
- packages/gi-site/src/components/ThemeVars/index.ts
- packages/gi-site/src/components/ThemeVars/useTheme.tsx
- packages/gi-site/src/pages/Dataset/Table.tsx
- packages/gi-site/src/pages/Home/Notification.tsx
- packages/gi-site/src/pages/Home/const.ts
- packages/gi-site/src/services/project.ts
- packages/gi-theme-antd/package.json
- packages/gi-theme-antd/src/components/const.ts
- packages/gi-theme-antd/src/components/index.tsx
- packages/gi-theme-antd/src/theme/config.js
- packages/gi-theme-antd/src/theme/green.js
- 新增「芒种绿」主题
- 解决「数据集」模块主题色一致问题
- 解决「主题设置」数据服务问题
> Chore： 主题问题修复

- packages/gi-assets-neo4j/src/services/Driver.tsx
- packages/gi-assets-neo4j/src/services/Initializer.ts
- packages/gi-assets-neo4j/src/services/Neo4jService.ts
- packages/gi-assets-tugraph/src/services/Initializer.tsx
- packages/gi-assets-tugraph/src/services/TuGraphService.ts
- packages/gi-sdk/src/components/EngineServer/Connect.tsx
- packages/gi-sdk/src/components/EngineServer/LoadGraph.tsx
- packages/gi-sdk/src/components/EngineServer/index.tsx
- packages/gi-sdk/src/components/EngineServer/utils.ts
- packages/gi-site/src/pages/Dataset/Create.tsx
- packages/gi-site/src/services/assets.ts
- 每个引擎的页面回填数据独立
- 规范了查询子图列表，图模型，图数据量逻辑
- 修改错误提示等问题
> Chore：修复引擎对接若干问题

- packages/gi-assets-basic/src/components/ActivateRelations/info.ts
- packages/gi-assets-basic/src/components/CanvasSetting/CanvasDoubleClick.tsx
- packages/gi-assets-basic/src/components/CanvasSetting/index.tsx
- packages/gi-sdk/src/typing.ts
- packages/gi-site/src/pages/Analysis/getAssets/getComponentsByAssets.ts
- packages/gi-site/src/pages/AssetsList/CartButton.tsx
- packages/gi-site/src/pages/AssetsList/CartContent.tsx
- packages/gi-site/src/pages/AssetsList/Detail.tsx
- packages/gi-site/src/pages/AssetsList/index.tsx
- packages/gi-site/src/pages/ServerCenter/index.tsx
https://github.com/antvis/G6VP/assets/10703060/0598c39e-4422-4a49-b036-e2db0a2419a9
> WIP：增加资产选购清单，用于快速生成模版

- packages/gi-assets-advance/src/components/AnalysisHistory/TemplateDrawer.tsx
- packages/gi-assets-advance/src/components/AnalysisHistory/info.ts
- packages/gi-assets-algorithm/src/NodesSimilarity/Component.tsx
- packages/gi-assets-basic/src/components/PropertyGraphInitializer/info.ts
fix: 运行历史记录时资产未添加到画布上的运行失败提示; 
perf: 历史记录资产和属性图计算资产增加语雀链接;
> fix: 运行历史记录时资产未添加到画布上的运行失败提示; perf: 历史记录资产和属性图计算资产增加语雀链接

- README.md
- packages/gi-assets-advance/CHANGELOG.md
- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/CHANGELOG.md
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-basic/CHANGELOG.md
- packages/gi-assets-basic/package.json
- packages/gi-assets-galaxybase/CHANGELOG.md
- packages/gi-assets-galaxybase/package.json
- packages/gi-assets-graphscope/CHANGELOG.md
- packages/gi-assets-graphscope/package.json
- packages/gi-assets-hugegraph/CHANGELOG.md
- packages/gi-assets-hugegraph/package.json
- packages/gi-assets-neo4j/CHANGELOG.md
- packages/gi-assets-neo4j/package.json
- packages/gi-assets-scene/CHANGELOG.md
- packages/gi-assets-scene/package.json
- packages/gi-assets-tugraph/CHANGELOG.md
- packages/gi-assets-tugraph/package.json
- packages/gi-common-components/CHANGELOG.md
- packages/gi-common-components/package.json
- packages/gi-httpservice/CHANGELOG.md
- packages/gi-httpservice/package.json
- packages/gi-sdk/CHANGELOG.md
- packages/gi-sdk/package.json
- 更新站点：2023-05-23
- 解决「历史路径分析」「模式匹配」等资产若干问题
- 新增「资产清单生成模版」功能
- 若干代码逻辑优化，bug修复
> release: site-2023-05-23

- packages/gi-cli/package.json
- packages/gi-cli/templates/src/index.tsx
- packages/gi-cli/templates/src/templates/MyTemplate.tsx
- packages/gi-cli/templates/src/templates/index.tsx
> feat(gi-cli): add custom template

- packages/gi-site/src/services/const.tsx
🐛 Bugfix
✨ Feature
🎨 Enhance
🔧 Chore
> Correct the access URL by removing the latest slash under online env

- packages/gi-site/.umirc.ts
- packages/gi-site/scripts/pre-build.mjs
> chore: upgrade g6 external

- packages/gi-assets-advance/package.json
- packages/gi-assets-advance/src/components/GraphAnnotation/Component.tsx
fix: 修复 annotation 资产 icon 偶尔显示不正常、连线连接位置不正常问题
> fix: 修复 annotation 资产 icon 偶尔显示不正常、连线连接位置不正常问题

- packages/gi-assets-advance/src/components/StructAnalysis/Component.tsx
- packages/gi-assets-advance/src/components/SubGraphLayout/Component.tsx
- packages/gi-assets-advance/src/components/SubGraphLayout/const.ts
- packages/gi-assets-advance/src/components/SubGraphLayout/utils.ts
- packages/gi-assets-advance/src/components/TableMode/Component.tsx
- packages/gi-assets-advance/src/components/ThemeSetting/Component.tsx
- packages/gi-assets-advance/src/components/ThemeSetting/typing.ts
- packages/gi-assets-algorithm/src/ClusterTable/index.tsx
- packages/gi-assets-algorithm/src/NodesClustering/Component.tsx
- packages/gi-assets-basic/src/components/ActivateRelations/activate-relations-v2.ts
- packages/gi-assets-basic/src/components/ChartAnalysis/Charts/ColumnChart.tsx
- packages/gi-assets-basic/src/components/ChartAnalysis/Charts/LineChart.tsx
- packages/gi-assets-basic/src/components/ChartAnalysis/Charts/index.tsx
- packages/gi-assets-basic/src/components/ChartAnalysis/index.less
- packages/gi-assets-basic/src/components/GrailLayout/useComponents.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/SegmentedTabs.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/useComponents.tsx
- packages/gi-assets-basic/src/components/UadLayout/useComponents.tsx
- packages/gi-site/src/components/ThemeVars/useTheme.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/ComponentPanel.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ComponentPanel/index.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsCenter.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsSelector.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/constants.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.tsx
fix: bugfix，包括：
- 1，3，4，5，6，9 in https://github.com/antvis/G6VP/issues/295
- 2，3，5 in https://github.com/antvis/G6VP/issues/296
> fix: bugfix

- packages/gi-cli/templates/__tests__/validation/id.test.ts
- packages/gi-cli/templates/jest.config.js
- packages/gi-cli/templates/package.json
- packages/gi-cli/templates/package.json.tpl
- packages/gi-cli/templates/setupTests.js
- packages/gi-cli/templates/src/components/Counter/info.ts
- packages/gi-cli/templates/src/components/MyLayout/info.ts
- packages/gi-sdk/src/constants/info.ts
- packages/gi-sdk/src/index.tsx
提升研发体验
1. 导出 info type、category注解
使用方式:
```ts
import { Info } from '@antv/gi-sdk';
// 组件类型、元素类型、组件分类
Info.tyle.xxx
Info.category.xxx
```
**之前:**
> 没有任何提示，需要查阅相关文档才能知道如何填写
**之后**:
> 提供注解，能够看到每个类型的定义和使用案例
2. @antv/gi-cli 添加测试环境，在启动、构建前执行相关测试，提前规避问题
例如要求组件导出 key 值需要与 `info.id` 保持一致
> refactor: 资产开发体验提升

- packages/gi-assets-advance/CHANGELOG.md
- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/CHANGELOG.md
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-basic/CHANGELOG.md
- packages/gi-assets-basic/package.json
- packages/gi-assets-galaxybase/CHANGELOG.md
- packages/gi-assets-galaxybase/package.json
- packages/gi-assets-graphscope/CHANGELOG.md
- packages/gi-assets-graphscope/package.json
- packages/gi-assets-hugegraph/CHANGELOG.md
- packages/gi-assets-hugegraph/package.json
- packages/gi-assets-janusgraph/CHANGELOG.md
- packages/gi-assets-janusgraph/package.json
- packages/gi-assets-neo4j/CHANGELOG.md
- packages/gi-assets-neo4j/package.json
- packages/gi-assets-scene/CHANGELOG.md
- packages/gi-assets-scene/package.json
- packages/gi-assets-tugraph/CHANGELOG.md
- packages/gi-assets-tugraph/package.json
- packages/gi-cli/CHANGELOG.md
- packages/gi-cli/package.json
- packages/gi-common-components/CHANGELOG.md
- packages/gi-common-components/package.json
- packages/gi-httpservice/CHANGELOG.md
- packages/gi-httpservice/package.json
- packages/gi-sdk/CHANGELOG.md
- packages/gi-sdk/package.json
- packages/gi-theme-antd/CHANGELOG.md
- packages/gi-theme-antd/package.json
> feat: update site

- packages/gi-assets-advance/src/components/index.tsx
- packages/gi-assets-basic/src/components/FitCenterView/info.ts
- packages/gi-assets-basic/src/components/LayoutSwitch/Component.tsx
- packages/gi-assets-basic/src/components/Sankey/Component.tsx
- packages/gi-assets-basic/src/components/index.tsx
- packages/gi-assets-scene/src/MapMode/Component.tsx
- packages/gi-assets-scene/src/MapMode/L7Map/index.tsx
- packages/gi-assets-scene/src/index.tsx
- closes: #296 
- 解决 4，7，8，9，10 问题
> Perf：优化站点问题

- packages/gi-assets-advance/src/components/GraphAnnotation/Component.tsx
> fix: 首次加载标注资产时连线画布大小不准确

- packages/gi-site/.umirc.ts
- packages/gi-site/package.json
- packages/gi-site/src/layouts/SideNav.tsx
- packages/gi-site/src/pages/G6V5Demo/index.less
- packages/gi-site/src/pages/G6V5Demo/index.tsx
- pnpm-lock.yaml
> feat: G6v5 demo iframe

- packages/gi-httpservice/app/router.ts
- packages/gi-httpservice/app/service/graphscope.ts
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> Fixes the connection failure to the GraphScope engine

- packages/gi-assets-advance/src/components/TableMode/Component.tsx
- packages/gi-assets-advance/src/components/TableMode/registerMeta.ts
- fix: 修复页签分屏数据不展示问题
- feat: 增加页签分屏路由配置项  https://github.com/antvis/G6VP/issues/107
> fix: TableMode 页签分屏问题

- packages/gi-assets-tugraph-analysis/src/components/LoopDetectionDemo/Component.tsx
> feat(tugraph-analysis): 环路检测数据包切换为批量发送

- packages/gi-assets-basic/src/components/LayoutSwitch/Component.tsx
- packages/gi-site/src/hooks/common.ts
- packages/gi-site/src/hooks/useNodeModule.ts
- Fix：LayoutSwitch Key ：https://github.com/antvis/G6VP/issues/334
> feat: update key

- packages/gi-assets-basic/README.md
- packages/gi-assets-basic/src/deploys/Esm.tsx
- packages/gi-assets-basic/src/deploys/Html.tsx
- packages/gi-assets-basic/src/deploys/Umd.tsx
- packages/gi-assets-basic/src/deploys/index.ts
- packages/gi-assets-basic/src/index.tsx
- packages/gi-sdk/src/process/loaderAssets.tsx
- packages/gi-sdk/src/typing.ts
- packages/gi-site/src/components/Navbar/ExportSdk.tsx
- packages/gi-site/src/hooks/common.ts
- packages/gi-site/src/pages/Analysis/hooks/useContext.ts
- packages/gi-site/src/services/assets.ts
> feat: update deploys

- packages/gi-assets-basic/src/components/Initializer/Component.tsx
- packages/gi-assets-basic/src/components/Initializer/registerMeta.ts
- packages/gi-sdk/src/process/index.ts
- packages/gi-sdk/src/process/schema.ts
- packages/gi-sdk/src/process/transGraphDataBySchemaMate.ts
- Initializer 增加字段映射配置逻辑，打开配置读取 schema 的 meta 信息，转换映射信息
> feat: Initializer 增加字段映射配置逻辑

- packages/gi-site/scripts/link.mjs
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> fix: 替厨神修复联调link阶段报错的问题

- packages/gi-assets-algorithm/src/NodesClustering/Component.tsx
- packages/gi-assets-basic/src/components/FilterPanel/Component.tsx
- packages/gi-assets-basic/src/components/FilterPanel/FilterSelection.tsx
- packages/gi-assets-basic/src/components/FilterPanel/utils.ts
- packages/gi-assets-basic/src/components/OverView/Filter.tsx
- packages/gi-assets-basic/src/components/SegmentedLayout/component.tsx
- packages/gi-common-components/src/CommonStyleSetting/GroupSelect/index.tsx
- packages/gi-sdk/src/GISDK.tsx
- packages/gi-sdk/src/context.tsx
- packages/gi-sdk/src/typing.ts
- packages/gi-site/src/components/AssetsCenter/index.less
- packages/gi-site/src/components/SegmentedTabs/index.less
- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsSelector.tsx
- packages/gi-site/src/pages/Analysis/MetaPanel/index.less
* 类型修正
* 将 GraphinData 改为 GIGraphData
* context 支持传入范型
* gi-site 点击删除资产不会弹出下方选择器
* 部分样式修正
> chore: types and small issues fix

- packages/gi-assets-tugraph/src/services/CypherQuery.ts
- packages/gi-assets-tugraph/src/services/Initializer.tsx
- packages/gi-assets-tugraph/src/services/TuGraphService.ts
- packages/gi-httpservice/app/controller/tugraph.ts
- packages/gi-httpservice/app/router.ts
- packages/gi-httpservice/app/service/tugraph.ts
- packages/gi-portal/package.json
- packages/gi-portal/src/pages/const.tsx
- packages/gi-portal/src/pages/index.tsx
- packages/gi-sdk/src/process/getSchemaGraph.ts
- packages/gi-site/src/pages/Analysis/index.tsx
- 支持 Token 刷新：closes: #373 
- 支持 3.5 引擎的邻居查询，closes: https://github.com/antvis/G6VP/issues/375
- 修复 Schema Graph 的展示问题 
- 支持通过URL参数初始化查询
> Chore：TuGraph 问题修复

- packages/gi-common-components/src/CommonStyleSetting/GroupSelect/index.tsx
* 修复 GroupSelect 在多选模式下默认值异常的问题
* 顺便调整了写法
> fix: fix issue occur when multiple mode with defaultValue

- docs/open-source-platform.md
- docs/open-source-platform.zh-CN.md
> feat: add open source graph visualization platform

- packages/gi-site/.must.config.js
- packages/gi-site/src/hooks/useHtml.ts
- 修复 html 模式导出异常问题
- 调整 must 脚本
> fix: 修复 html模式 导出异常

- package.json
- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-basic/package.json
- packages/gi-assets-basic/src/components/ActivateRelations/ActivateRelations.tsx
- packages/gi-assets-graphscope/package.json
- packages/gi-assets-hugegraph/package.json
- packages/gi-assets-neo4j/package.json
- packages/gi-assets-scene/package.json
- packages/gi-assets-testing/package.json
- packages/gi-assets-tugraph-analytics/package.json
- packages/gi-assets-tugraph/package.json
- packages/gi-cli/templates/package.json
- packages/gi-cli/templates/package.json.tpl
- packages/gi-common-components/package.json
- packages/gi-httpservice/package.json
- packages/gi-sdk/package.json
- packages/gi-site/package.json
* 升级 Graphin 版本
* 接入 useBehaviorHook
> Chore: update graphin version

- packages/gi-site/src/components/Navbar/SaveWorkbook.tsx
> fix: fix issue that cannot save project if not exists graph

- packages/gi-sdk/src/process/common.ts
- packages/gi-sdk/src/typing.ts
- packages/gi-site/src/pages/Analysis/getAssets/getComponentsByAssets.ts
registerMeta 的 context 中透出了 `GIAC_ITEMS`, `GIAC_MENU_ITEMS`, `GIAC_CONTENT_ITEMS`，现在额外透出 `AUTO_ITEMS`
> feat: export AUTO_ITEMS from registerMeta context

- packages/gi-sdk-app/GI_EXPORT_CONFIG.json
- packages/gi-sdk-app/README.md
- packages/gi-sdk-app/index.html
- packages/gi-sdk-app/package.json
- packages/gi-sdk-app/src/Loading/index.less
- packages/gi-sdk-app/src/Loading/index.tsx
- packages/gi-sdk-app/src/index.tsx
- packages/gi-sdk-app/src/loaderAssets.tsx
- packages/gi-sdk-app/tsconfig.json
- packages/gi-sdk/src/components/Studio.tsx
- packages/gi-site/src/components/Navbar/ExportSdk.tsx
- 加载 JS 脚本，全局变量为 GI_SDK_APP
```html
<script src="https://gw.alipayobjects.com/os/lib/babel/standalone/7.19.2/babel.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/17.0.2/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/17.0.2/umd/react-dom.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/antv/gi-sdk-app/1.0.0/dist/index.min.js"></script>
```
- 加载 CSS 脚本
```html
<link rel="stylesheet" href="https://gw.alipayobjects.com/os/lib/antv/gi-sdk-app/1.0.0/dist/index.css" />
```
- 运行脚本，渲染得到应用
其中 `GI_EXPORT_CONFIG.json` 都是 [Insight](https://insight.antv.antgroup.com) 站点导出的配置，如下方代码所示，我们在本地构建了一个 Mock Server ，推荐用户自己构建服务，托管自己的站点应用
```html
<body>
<div id="root"></div>
<script type="text/babel">
const …
```
> feat: add gi-sdk-app

- packages/gi-site/.umirc.ts
- packages/gi-site/scripts/pre-build.mjs
- packages/gi-site/src/components/Navbar/ExportSdk.tsx
- packages/gi-site/src/hooks/common.ts
- packages/gi-site/src/hooks/useNodeModule.ts
> feat: update const

- packages/gi-assets-advance/src/components/AnalysisHistory/Component.tsx
- packages/gi-assets-advance/src/components/GremlinQuery/Component.tsx
- pnpm-lock.yaml
fix: history analysis assets container problem
修改其容器为画布区域，避免遮挡到侧边容器底部
> fix: history analyse assets container problem

- packages/gi-assets-advance/src/components/GremlinQuery/Component.tsx
- packages/gi-assets-advance/src/i18n/strings/en-US.json
- packages/gi-assets-advance/src/i18n/strings/zh-CN.json
- packages/gi-assets-advance/src/services/CypherQuery.ts
feat: gremlin query constraints
1. g.V()   ->    g.with('evaluationTimeout', 5000).V().limit(100)  我们额外加超时和limit
2. g.with('evaluationTimeout', 1000).V() -> g.with('evaluationTimeout', 1000).V().limit(100)  我们只加 limit
3.  g.V().limit(1)  -> g.with('evaluationTimeout', 5000).V().limit(1) 我们只加超时
4. g.with('evaluationTimeout', 1000).V().lmit(1) -> g.with('evaluationTimeout', 1000).V().lmit(1) 我们什么都不加
> feat: gremlin query constraints

- .husky/_/husky.sh
- .husky/pre-commit
- package.json
- pnpm-lock.yaml
配置 husky，阻止直接向 master 提交代码
执行效果：
> chore: add husky to forbid push to master branch directly

- packages/gi-site/package.json
> fix: fix script issue

- packages/gi-assets-advance/src/components/SubGraphLayout/utils.ts
- packages/gi-assets-advance/src/components/utils/csv.ts
- packages/gi-assets-algorithm/src/PatternMatch/Component.tsx
- packages/gi-assets-algorithm/src/utils/csv.ts
- packages/gi-assets-algorithm/src/utils/graph.ts
- packages/gi-assets-basic/src/components/Export/Component.tsx
- packages/gi-assets-basic/src/components/utils/csv.ts
- packages/gi-sdk/src/index.tsx
- packages/gi-sdk/src/utils/download.ts
- packages/gi-sdk/src/utils/index.ts
- packages/gi-site/src/components/Navbar/ExportSdk.tsx
- packages/gi-site/src/components/utils.ts
* gi-sdk 导出 `common`.`createDownload` 方法，用于统一处理下载任务
* 修复模式识别无法下载匹配模式的问题
* 模式识别选择状态下，选中边时，自动选中两边端点
https://github.com/antvis/G6VP/assets/25787943/45c4a069-20fb-489a-9ba3-988bb7625be0
> fix: fix issues with pattern match

- packages/gi-site/src/pages/Workspace/Projects.tsx
> style: adjust workbook card style

- packages/gi-site/src/i18n/strings/en-US.json
- packages/gi-site/src/i18n/strings/zh-CN.json
- packages/gi-site/src/services/user.tsx
调整 VIP 资产获取流程
之前会自动弹出新的网页，有点流氓
现在会先询问是否获取 VIP 资产
> refactor: adjust vip assets retrieve process

- packages/gi-assets-scene/src/Timebar/Component.tsx
- packages/gi-assets-scene/src/Timebar/control/index.tsx
- packages/gi-assets-scene/src/Timebar/control/panel/index.tsx
- packages/gi-assets-scene/src/Timebar/control/utils.ts
- packages/gi-assets-scene/src/Timebar/registerMeta.ts
- packages/gi-assets-tugraph/src/services/CypherQuery.ts
- packages/gi-httpservice/app/service/tugraph.ts
- packages/gi-httpservice/app/service/xlab.ts
- packages/gi-httpservice/app/tugraph.utils.ts
- packages/gi-httpservice/config/plugin.ts
- packages/gi-site/src/services/assets.ts
fix: tugraph cypher query supports paths
> fix: tugraph cypher query supports paths

- packages/gi-assets-scene/package.json
- packages/gi-assets-scene/src/Timebar/Component.tsx
- packages/gi-assets-scene/src/Timebar/control/index.tsx
- packages/gi-assets-scene/src/Timebar/control/panel/index.tsx
- packages/gi-assets-scene/src/Timebar/control/utils.ts
- packages/gi-assets-scene/src/Timebar/registerMeta.ts
feat: 时间轴支持显示/隐藏模式; fix: 时间轴单个节点或边上若无时间字段，则不应被时间轴影响
> feat: 时间轴支持显示/隐藏模式; fix: 时间轴单个节点或边上若无时间字段，则不应被时间轴影响

- packages/gi-common-components/src/FormilyForm/FormCollapse/index.tsx
fix: 样式配置面板 collapse panel 无法打开问题
> fix: 样式配置面板 collapse panel 无法打开问题

- packages/gi-assets-basic/src/components/MiniMap/Component.tsx
- packages/gi-assets-basic/src/components/MiniMap/index.tsx
- packages/gi-assets-basic/src/components/MiniMap/registerMeta.ts
> perf: minimap支持配置定位

- packages/gi-site/src/components/Navbar/ExportSdk.tsx
closes: https://github.com/antvis/G6VP/issues/488
> fix: export html bug

- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/SegmentFilter.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/index.less
- packages/gi-assets-basic/src/components/PathAnalysis/registerMeta.ts
- packages/gi-common-components/src/Icon/index.tsx
- packages/gi-common-components/src/NodeSelectionWrap/index.tsx
> Assets: PathAnalysis

- package.json
- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-basic/package.json
- packages/gi-assets-galaxybase/package.json
- packages/gi-assets-graphscope/package.json
- packages/gi-assets-hugegraph/package.json
- packages/gi-assets-neo4j/package.json
- packages/gi-assets-scene/package.json
- packages/gi-assets-tugraph-analytics/package.json
- packages/gi-assets-tugraph/package.json
- packages/gi-cli/templates/package.json
- packages/gi-cli/templates/package.json.tpl
- packages/gi-common-components/package.json
- packages/gi-httpservice/package.json
- packages/gi-sdk/package.json
- packages/gi-site/.umirc.ts
- pnpm-lock.yaml
commit https://github.com/antvis/G6VP/commit/6bb07f33495f4d1255548ba0742b25b8d5cb1b07 修改了 external 配置，导致启动失败
> fix: fix error that gi-site lodash is undefined

- packages/gi-assets-advance/src/components/GraphAnnotation/Component.tsx
- packages/gi-assets-advance/src/components/GraphAnnotation/registerMeta.ts
feat: annotation supports default title and content from properties
> feat: annotation supports default title and content from properties

- packages/gi-assets-advance/src/components/AnalysisHistory/Component.tsx
- packages/gi-assets-advance/src/components/Sheetbar/Component.tsx
- packages/gi-assets-advance/src/components/Sheetbar/registerMeta.ts
- packages/gi-assets-advance/src/components/Sheetbar/utils.ts
- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/components/RichContainer/index.less
- packages/gi-assets-basic/src/components/RichContainer/registerMeta.ts
- Support sheetbar
- The style still needs to be adjusted
> feat: support sheetbar

- docs/CONTRIBUTING.md
- packages/gi-assets-advance/src/components/AnalysisHistory/Component.tsx
- packages/gi-assets-advance/src/components/Sheetbar/Component.tsx
- packages/gi-assets-advance/src/components/Sheetbar/registerMeta.ts
- packages/gi-assets-advance/src/components/Sheetbar/utils.ts
- packages/gi-assets-basic/src/components/EdgeMerge/Component.tsx
- packages/gi-assets-basic/src/components/EdgeMerge/index.tsx
- packages/gi-assets-basic/src/components/EdgeMerge/info.ts
- packages/gi-assets-basic/src/components/EdgeMerge/registerMeta.ts
- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/components/RichContainer/index.less
- packages/gi-assets-basic/src/components/RichContainer/registerMeta.ts
- packages/gi-assets-basic/src/components/index.tsx
- Add Third-party asset development documents
- Add EdgeMerge  Asset
> Feat：EdgeMerge Asset

- packages/gi-assets-basic/src/components/ContextMenu/ContextMenu.tsx
- packages/gi-assets-basic/src/components/ContextMenu/index.less
- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/components/RichContainer/Toolbar.tsx
- packages/gi-assets-basic/src/components/RichContainer/index.less
- packages/gi-assets-basic/src/components/ShortcutKeys/Component.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
> fix: 更新业务布局组件

- packages/gi-site/src/components/Navbar/SaveWorkbook.tsx
- packages/gi-site/src/components/Navbar/WorkbookNav.tsx
- packages/gi-site/src/services/const.tsx
- packages/gi-site/src/services/dataset.tsx
- packages/gi-site/src/services/project.ts
- packages/gi-site/src/services/user.tsx
- packages/gi-site/src/services/utils.ts
> feat: 云端存储服务兼容

- packages/gi-site/src/services/const.tsx
- packages/gi-site/src/services/user.tsx
> fix: 内网用户服务切换逻辑

- packages/gi-site/src/services/user.tsx
> feat: 修改环境自动切换逻辑

- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
- packages/gi-common-components/src/Handler/index.tsx
> fix: Handle 组件支持自定义图标

- packages/gi-assets-basic/src/components/DownLoad/Component.tsx
- packages/gi-assets-basic/src/components/DownLoad/registerMeta.ts
- packages/gi-assets-basic/src/components/utils/graph.ts
- packages/gi-assets-basic/src/i18n/strings/en-US.json
- packages/gi-assets-basic/src/i18n/strings/zh-CN.json
feat: 下载图片支持配置下载全图和图片带指定 copyright 图片
> feat: 下载图片支持配置下载全图和图片带指定 copyright 图片

- packages/gi-site/src/components/Navbar/Language.tsx
- packages/gi-site/src/i18n/strings/en-US.json
- packages/gi-site/src/i18n/strings/zh-CN.json
- packages/gi-site/src/pages/Workspace/Recover.tsx
> feat: add security alert

- packages/gi-assets-advance/package.json
- packages/gi-assets-advance/src/components/GraphAnnotation/Component.tsx
> fix: 无法取消 tag

- packages/gi-site/src/hooks/useUserInfo.ts
> fix: fix issue that assets modify not effect

- packages/gi-site/src/pages/Dataset/Create.tsx
> feat: 支持通过url查询参数选择引擎

- packages/gi-assets-algorithm/src/NodesSimilarity/resultTable.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/SegmentFilter.tsx
- packages/gi-common-components/src/NodeSelectionWrap/index.tsx
* NodeSelectionWrap 支持搜索
* 路径相似度支持高亮节点
> fix: path query and node similarity issues

- packages/gi-assets-basic/src/components/LayoutSwitch/Component.tsx
布局切换支持 filter 参数
组件复用时可以对布局类型进行过滤
**过滤前**
**过滤后**
```tsx
import React from 'react';
import { components } from '@antv/gi-assets-basic';
const { info, registerMeta, component: Component } = components.LayoutSwitch;
export default {
info: {
...info,
id: 'OverrideLayoutSwitch',
},
registerMeta,
component: (args: Parameters<typeof Component>[0]) => {
return (
<Component
{...args}
filter={(layout) => ['Force2', 'Radial', 'Concentric', 'Circular', 'Dagre'].includes(layout)}
/>
);
},
};
```
> refactor: layout switch support filter

- packages/gi-assets-basic/src/components/ForceSimulation/Component.tsx
- packages/gi-assets-basic/src/components/common/handlePinNode.tsx
- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
> feat: drag and pin node

- packages/gi-assets-neo4j/src/services/NeighborsQuery.ts
fix undefined in neo4j neighbor query
| <img width="908" alt="image" src="https://github.com/antvis/G6VP/assets/3632490/1162c83f-6646-42a9-be94-2477cf647664">    | <img width="847" alt="image" src="https://github.com/antvis/G6VP/assets/3632490/e99a1a8c-e54a-4c8e-b6ea-e4e59536baf4">   |
> 🐛 Bugfix: fix undefined in neo4j neighbor query

- packages/gi-assets-neo4j/src/services/Driver.tsx
🐛 Bugfix
🔧 Chore
fix neo4j schema edges missing
| ![image](https://github.com/antvis/G6VP/assets/3632490/2abc938e-b9ac-4502-b378-e979e7288264)    | ![image](https://github.com/antvis/G6VP/assets/3632490/3841ed36-3368-4032-bdc9-1bab02b1cb50)   |
> 🐛 Bugfix: fix neo4j schema edges missing

- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
✨ Feature
- [1 ] New feature
Filter container tab get local data for default checked
🎨 Enhance
🐛 Bugfix
🔧 Chore
> feat: add local data map & format code

- packages/gi-assets-basic/CHANGELOG.md
- packages/gi-assets-basic/package.json
- packages/gi-common-components/CHANGELOG.md
- packages/gi-common-components/package.json
- packages/gi-sdk/CHANGELOG.md
- packages/gi-sdk/package.json
- pnpm-lock.yaml
> chore: change log

- packages/gi-sdk-app/package.json
> chore: update gi-sdk-app version

- packages/gi-sdk-app/src/index.tsx
- packages/gi-sdk/src/GISDK.tsx
- packages/gi-sdk/src/typing.ts
🐛 Bugfix
fix GISDK keep render
| ❌     | ![image](https://github.com/user-attachments/assets/318d9599-b557-40e2-bacf-f056b0acd263) |
> fix: GISDK keep render
