- packages/gi-assets-basic/src/components/SideTabs/SideContainer.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1.  展开、折叠side tabs时，canvas的宽高没有对应的更新，导致点边的显示位置有偏差。见对比截图
2. 折叠side tabs时side tabs的transition动画没有生效
| ![Untitled8](https://user-images.githubusercontent.com/3103676/210323114-3e6ad2d4-c08d-44ea-9fdb-5b6c5477bef2.gif)|  ![Untitled9](https://user-images.githubusercontent.com/3103676/210323175-ce811c48-b059-48d4-8025-a58436daaedc.gif)  |
> fix: update canvas width when toggle tabs visibility

- packages/gi-assets-basic/src/components/ActivateRelations/ActivateRelations.tsx
- packages/gi-assets-basic/src/components/ActivateRelations/Component.tsx
- packages/gi-assets-basic/src/components/ActivateRelations/activate-relations-v2.ts
- packages/gi-assets-basic/src/components/ActivateRelations/registerMeta.ts
- packages/gi-common-components/src/SchemaField/ModifierPicker.tsx
- packages/gi-common-components/src/SchemaField/index.tsx
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
基于G6的activate-relations做了以下升级改造
1. 支持多选进行高亮
2. 支持分别定义高亮时上下游进行扩展的度数
> feat: 元素高亮资产支持配置多选和上下游度数

- packages/gi-assets-hugegraph/src/components/Connect.tsx
fix: hugegraph 的 G6VP http 地址暂时需要配置
> fix: hugegraph 的 G6VP http 地址暂时需要配置

- packages/gi-assets-advance/package.json
- packages/gi-assets-advance/src/components/Assistant/Component.tsx
- packages/gi-assets-advance/src/components/Assistant/Dialog/index.less
- packages/gi-assets-advance/src/components/Assistant/Dialog/index.tsx
- packages/gi-assets-advance/src/components/Assistant/Dialog/input.tsx
- packages/gi-assets-advance/src/components/Assistant/Dialog/list.tsx
- packages/gi-assets-advance/src/components/Assistant/Dialog/message.tsx
- packages/gi-assets-advance/src/components/Assistant/Header/index.less
- packages/gi-assets-advance/src/components/Assistant/Header/index.tsx
- packages/gi-assets-advance/src/components/Assistant/constants.ts
- packages/gi-assets-advance/src/components/Assistant/context.ts
- packages/gi-assets-advance/src/components/Assistant/hooks/useController.ts
- packages/gi-assets-advance/src/components/Assistant/index.less
- packages/gi-assets-advance/src/components/Assistant/index.ts
- packages/gi-assets-advance/src/components/Assistant/info.ts
- packages/gi-assets-advance/src/components/Assistant/registerMeta.ts
- packages/gi-assets-advance/src/components/Assistant/utils/extractCodeBlocks.ts
- packages/gi-assets-advance/src/components/Assistant/utils/message.ts
- packages/gi-assets-advance/src/components/Assistant/utils/prompt.ts
- packages/gi-assets-advance/src/components/index.tsx
- packages/gi-assets-advance/src/services/OpenAIQuery.ts
**资产类别**：自运行组件
**配置项**：
* `API KEY`: [OpenAI API KEY](https://platform.openai.com/account/api-keys)
* `数据服务`
* `Logo`: 自定义图标 URL 地址
* `尺寸`: 图标尺寸
* `偏移量`: 图标偏移量
* `可拖拽`: 图标及对话窗口是否可拖拽
* `欢迎语`: 用户欢迎语，会作为第一句向用户发起的对话
* `提示词`: chatGPT 提示词
**使用方式**
1. 配置 `API KEY` (必填) 及其他配置项
2. 点击图标唤起对话窗口
**演示视频**
- 本视频使用 Neo4J 作为数据源
https://user-images.githubusercontent.com/25787943/234010672-8d58a06e-4fe4-44c0-8007-12adc1b825c7.mov
> feat: add ai assistant based by chatGPT

- packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts
In order to add an image type icon to the nodes in the canvas, the relevant line must be added.
> node Image Type bug

- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/index.tsx
> fix: 取消容器勾选时集成的子资产缓存问题

- .changeset/config.json
- README.md
- package.json
- packages/gi-assets-advance/package.json
- packages/gi-assets-algorithm/package.json
- packages/gi-assets-basic/package.json
- packages/gi-assets-galaxybase/package.json
- packages/gi-assets-graphscope/package.json
- packages/gi-assets-hugegraph/package.json
- packages/gi-assets-neo4j/package.json
- packages/gi-assets-scene/package.json
- packages/gi-assets-testing/package.json
- packages/gi-assets-tugraph/package.json
- packages/gi-common-components/package.json
- packages/gi-mock-data/package.json
- packages/gi-portal/package.json
- packages/gi-sdk/package.json
- packages/gi-site/package.json
- packages/gi-theme-antd/package.json
- packages/my-custom-server/package.json
- pnpm-workspace.yaml
配置 [changeset](https://pnpm.io/using-changesets) 进行多包发布
发布方式如下：
1. 选择要发布的子包
```bash
pnpm changeset
```
2. 选择版本号类型[major/minor/patch]
> 一般小版本就是 patch，直接回车两下就好。然后输入 `Summary`
确认后再回车
此时暂存区可以看到生成的 changeset 文件(文件名随机)，记录了版本信息和描述
3. 更新版本号并生成 changelog
```bash
pnpm changeset version
```
执行完成后可以看到所有需要发布的包，其 package.json 中版本号已经更新
4. 执行发布
```bash
pnpm publish -r
```
此步骤需要确保需要发布的子包都已经正确构建，为了简便，可以在其 `package.scripts` 中添加 `"prepublishOnly": "npm run build"` 来自动执行
5. 将发布过程产生的变动文件到主分支
> chore: update publish process

- packages/gi-site/src/pages/AssetsList/Detail.tsx
- fix: 资产列表重复选择同一个资产展示异常问题
Tree 中重复选中为取消选中，增加取消判空
> fix: 资产列表重复选择同一个资产展示异常问题

- packages/gi-site/src/pages/Analysis/MetaPanel/ContainerPanel/AssetsCenter.tsx
> fix: 容器配置AssetsCenter重复渲染问题

- packages/gi-site/src/pages/Assets/Cards.tsx
- packages/gi-site/src/pages/Assets/Form.tsx
- packages/gi-site/src/pages/Assets/Table.tsx
- packages/gi-site/src/pages/Assets/Upload.tsx
- packages/gi-site/src/pages/Assets/index.tsx
- packages/gi-site/src/pages/Dataset/Table.tsx
- packages/gi-site/src/pages/Template/Cards.tsx
- packages/gi-site/src/pages/Workspace/Projects.tsx
- packages/gi-site/src/services/dataset.tsx
关联 Issue: https://github.com/antvis/G6VP/issues/284
优化内容：
* 数据集支持重命名，添加创建时间列，支持排序
* 工作簿支持重命名
* 资产管理支持现有编辑，卡片模式样式统一
* 模版卡片卡片样式统一
> refactor: gi-site 若干细节优化

- packages/gi-assets-scene/src/Timebar/control/index.tsx
迁移时 useEffect 依赖项错误导致 G2 Chart 重复渲染造成卡顿
> fix: 修复导致 timebar 卡顿的问题

- packages/gi-assets-scene/src/Timebar/Component.tsx
- packages/gi-assets-scene/src/Timebar/control/chart/index.tsx
- packages/gi-assets-scene/src/Timebar/control/index.tsx
- packages/gi-assets-scene/src/Timebar/control/panel/helper.ts
- packages/gi-assets-scene/src/Timebar/control/panel/index.tsx
- packages/gi-assets-scene/src/Timebar/control/utils.ts
- packages/gi-assets-scene/src/Timebar/registerMeta.ts
- packages/gi-assets-scene/src/Timebar/types.ts
之前不生效主要是因为在 GI 这边通过 `type:field` 的格式来区分节点字段和边字段
在传入 G2 schema 中为未进行处理导致找不到 encode 字段
> fix: 修复timebar配置不生效问题

- packages/gi-common-components/src/GroupContainer/ExpressionGroup.tsx
- packages/gi-common-components/src/GroupContainer/index.tsx
- packages/gi-common-components/src/GroupContainer/utils.ts
- packages/gi-common-components/src/Utils/getAllkeysBySchema.ts
- packages/gi-sdk/src/process/filterByRules.ts
- packages/gi-sdk/src/process/schema.ts
我看之前的逻辑，似乎是打算把属性名和属性类型通过 `-` 拼接在一起，不过实际上并没有做这步操作，导致全部属性规则都是 string 类型。
> feat: 分组规则支持属性路径，修复分组规则问题

- README.md
- package.json
- pnpm-lock.yaml
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在 #355 后，协作者们的开发环境应该统一（i.e. Node 16 & pnpm 8）了，于是`pnpm-lock.yml`文件应该尽量保持不动，所以我在本地先删除了该文件，并运行`pnpm i`重新生成。
以我有限的经验来说，lock文件是不应该经常变动的，之前总是能在proposed changes里看到它的身影，应该是协作者之间的开发环境不统一导致。除了影响开发体验外，1.75MB的`pnpm-lock.yml`还因为经常被提交到commit中生成了许多blob文件，增加了Git仓库的体积，加长了初次clone、日常fetch和push的时间（在网络环境欠佳的时候尤其明显）。
这个PR希望能终结`pnpm-lock.yml`频繁改动的现象。希望各位协作者能在本地试试看：
1. `gh pr checkout 361`
2. 确保本地开发环境是 Node 16 和 pnpm 8（请看这个分支下的README）
3. `pnpm install --force`（等价于先删除`node_modules`再`pnpm install`）
4. `pnpm run start`
然后确认两件事：(1) `pnpm-lock.yml`有没有被改动；(2)项目能不能跑起来。
@andyhuang18 @wj23027 @pomelo-nwu @yangzy0603 @Yanyan-Wang 
N.A.
> chore: 在建议的开发环境下重新生成`pnpm-lock.yml`

- packages/gi-common-components/src/GroupContainer/index.less
- packages/gi-common-components/src/GroupContainer/index.tsx
* 新增`重置`按钮，重置后仅保留默认样式
* 调整按钮样式，关闭滚动条
> feat: support clear default infer element style

- packages/gi-sdk/README.md
- packages/gi-sdk/src/components/Studio.tsx
- packages/gi-sdk/src/index.tsx
- packages/gi-sdk/src/process/loaderAssets.tsx
- packages/gi-site/src/components/Navbar/ExportSdk.tsx
增加 Studio 组件，用户根据约定，只需要传入接口服务即可通过 ID 获得全部的渲染信息
通过接口，获得应用渲染的配置参数，从而让用户可以这么实现
```jsx
export default () => {
return <window.GISDK.Studio id="xxxxx" service={getProject} />;
};
```
组件属性说明
- id：studio 的 唯一 id，可以通过接口获得全部的配置参数
- service： 第三方托管平台提供的接口，类型：`POST`
```js
// 入参
const request = {
id: 'app-xxx',
};
// 出参
const response = {
workbook: {
id: 'd3a818ea-f833-4229-85ea-a6670dae4a18',
name: 'GI',
activeAssetsKeys: {},
projectConfig: {
nodes: [],
edges: [],
components: [],
},
themes: [],
},
dataset: {
id: 'ds_f16fce61-aa3e-420d-a6cc-6b409f9aa37e',
engineContext: {
engineId: 'R+',
schemaData: {},
},
data: {},
},
deps: {
react: '17.x',
'react-dom': '17.x',
localforage: '1.10.0',
antd: '4.24.8',
'@antv/gi-theme-antd': '0.4.2',
'@antv/g6': '4.8.14',
'@antv/graphin': '2.7.16',
'@antv/gi-sdk': …
```
> feat: Add Studio Component

- packages/gi-site/.must.config.js
- packages/gi-site/src/hooks/useCodeSandbox.ts
- packages/gi-site/src/i18n/index.ts
- 恢复被翻译脚本误翻译的文案
- 调整翻译脚本配置，防止注释写法的文案被误翻译，例如以下场景：
> fix: umd 模式导出内容缺失

- packages/gi-assets-galaxybase/src/pages/update.ts
- packages/gi-sdk/src/index.tsx
声明全局 GISDK，避免通过如下方法接入 GISDK 时出现类型问题：
```
<window.GISDK />
```
> feat: global declare GISDK

- packages/gi-common-components/src/CommonStyleSetting/ColorInput/index.tsx
ColorInput 新增 x-component-props 选项： colorType
默认值为 rgba
指定为 `hex` 时，返回颜色值为 16 进制格式
```js
{
title: 'Color',
type: 'string',
'x-decorator': 'FormItem',
'x-component': 'ColorInput',
default: DEFAULT_STYLE.color,
'x-component-props': {
colorType: 'hex',
},
}
```
> feat: color input support specific color type of rgba or hex by x-component-props

- packages/gi-common-components/src/CommonStyleSetting/index.tsx
添加边样式分组时，`defaultNodeConfig` 作为边 polyfill 会导致错误
> fix: fix issue that may crash when add new edge style group

- packages/gi-sdk/src/process/services.ts
https://github.com/antvis/G6VP/pull/418 对资产进行按需导出，导致 `getServiceOptionsByEngineId` options 可能为空，这里添加默认值
> fix: add alternative value for defaultValue

- packages/gi-assets-basic/src/components/ZoomIn/Component.tsx
- packages/gi-assets-basic/src/components/ZoomOut/Component.tsx
- packages/gi-sdk/package.json
- packages/gi-sdk/src/index.tsx
- packages/gi-sdk/src/utils/index.ts
- packages/gi-sdk/src/utils/shortcuts.ts
- packages/gi-site/src/components/Navbar/SaveWorkbook.tsx
- packages/gi-site/src/components/Navbar/Share.tsx
- pnpm-lock.yaml
支持快捷键，从 `gi-sdk` 导出 `Shortcuts` 和 `useShortcuts`。
用法：
```ts
import { Shortcuts, useShortcuts } from '@antv/gi-sdk';
Shortcuts.on('command+s', ()=>{
// do something
});
useShortcuts('command+s', ()=>{
// do something
});
```
添加了默认快捷键：
`command+s`, `ctrl+s` ➡️ 保存项目
`command+shift+s`, `ctrl+shift+s` ➡️ 备份
`command+=`, `ctrl+=` ➡️ 放大画布
`command+-`, `ctrl+-` ➡️ 缩小画布
> ⚠️ 重复绑定时会覆盖掉已有的快捷键
> feat: support shortcuts

- .github/workflows/stats.yml
每周四晚上20点统计每周活跃情况，报告默认会存到 `workflows/weekly-stats` 分支下，以当日日期命名
报告示例：
> chore: add weekly stats

- packages/gi-assets-basic/src/components/ContextMenu/Container.tsx
🐛 Bugfix
存在问题： 抽屉中GISDK生成的图销毁后导致画布上的右键菜单无法出现
React.createRef 只能获取到最初渲染时的值，而不能获取到最新的值。改用 React.useRef 获取到最新的值。
效果图：
> fix: 修复右键菜单没出现的问题

- packages/gi-assets-algorithm/src/CommunityDetection/Component.tsx
- packages/gi-assets-algorithm/src/NodeImportance/Component.tsx
- packages/gi-assets-basic/src/components/LayoutSwitch/Component.tsx
`@antv/algorithm` 中 ilouvain 算法会修改原始图数据，写入 `node.properties.nodeType` 属性，可能会出现无法写入的情况，导致异常：
> Cannot add property nodeType, object is not extensible
> fix: fix issue that may cause ilouvain crash which object is not extensible

- packages/gi-site/src/pages/Assets/Form.tsx
- packages/gi-site/src/pages/Assets/Table.tsx
- packages/gi-site/src/pages/Assets/index.tsx
- UMD 名作为资产全局唯一性标识 不允许修改，否则修改操作无法满足预期
- 修改后 localStorage 中的 GI_ASSETS_PACKAGES  仍保持 Record<umdName，assetInfo> 的数据结构，消费时再转换成 Array
> fix(gi-site): 修复资产管理编辑修改不生效

- packages/gi-assets-algorithm/src/PatternMatch/Component.tsx
> fix: fix tabs pane label that cannot click

- packages/gi-site/scripts/link.mjs
`link` 和 `unlink` 操作不再修改 GI 一方资产依赖版本号
之前 `link` 进来的项目在 `unlink` 后需要手动将 `"workspace:*"` 修改为对应版本号
> refactor: link and unlink won't modify dependencies version

- packages/gi-assets-basic/package.json
- packages/gi-assets-basic/src/components/OperatorHeader/WrapContainer.tsx
- packages/gi-assets-basic/src/components/UIComponents/DivContainer/index.tsx
- packages/gi-sdk/src/components/Studio.tsx
- packages/gi-sdk/src/components/const.ts
- packages/gi-sdk/src/i18n/strings/en-US.json
- packages/gi-sdk/src/i18n/strings/zh-CN.json
- pnpm-lock.yaml
容器配置中针对 DIV 容器新增 **可拖拽（仅DIV有效）** 以及 **拖拽生效区域**。
效果如下：
> feat: 容器配置增加 DIV 容器支持拖拽

- packages/gi-assets-algorithm/src/PatternMatch/Component.tsx
之前问题：
抽屉里的模式匹配销毁后（切换到其他组件），会设置画布为 previousSize，但 previousSize 初始值为 500*500，并没有更新为画布实际的尺寸。
https://github.com/antvis/G6VP/blob/4324266bab3c7db13e28fe3aeb788611c8b4e4cd/packages/gi-assets-algorithm/src/PatternMatch/Component.tsx#L531-L541
https://github.com/antvis/G6VP/assets/25787943/d6817c5b-a242-4aea-9dad-13407f8a057c
> fix: fix issue that set wrong graph size when pattern match unmounted

- packages/gi-assets-advance/package.json
- packages/gi-assets-advance/src/components/GremlinQuery/Component.tsx
fix: 若未配置 timeout 和 limit 可配，则 gremlinQuery 不自动增加相关约束
> fix: 若未配置 timeout 和 limit 可配，则 gremlinQuery 不自动增加相关约束

- packages/gi-assets-basic/src/components/Placeholder/Component.tsx
- packages/gi-assets-basic/src/components/Placeholder/index.less
- packages/gi-assets-basic/src/components/Placeholder/registerMeta.ts
- packages/gi-assets-basic/src/i18n/strings/en-US.json
- packages/gi-assets-basic/src/i18n/strings/zh-CN.json
`gi-assets-basic` placeholder 修正
* 样式修正，修复了在 GISDK 容器尺寸较小时 placeholder 溢出的问题
* 修正了 className 命名拼写错误问题
* 新增`文本颜色`和`间距`配置项
> fix: fix layout of placeholder in small size

- packages/gi-sdk/src/typing.ts
调整 LayoutConfig 类型定义
在注册了自定义布局后，会出现类型错误，因此这里加上 `string` 类型支持
> refactor: adjust LayoutConfig type definition

- packages/gi-assets-algorithm/src/NodesSimilarity/Component.tsx
- packages/gi-assets-algorithm/src/NodesSimilarity/registerMeta.ts
- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/index.less
- packages/gi-assets-basic/src/components/PathAnalysis/registerMeta.ts
- packages/gi-common-components/src/NodeSelectionWrap/index.less
- packages/gi-common-components/src/NodeSelectionWrap/index.tsx
- packages/gi-common-components/src/index.ts
节点选择新增`标签格式化`选项
主要针对`路径分析`和`节点相似度`组件
默认情况下，`标签映射` 同时设置了节点选择器的 `label` 和 `value`
启用该选项后，可以对 `label` 进行定义，支持同时设置`主标签`和`副标签`
> refactor: node selection support config label formatter; style adjust

- packages/gi-assets-algorithm/src/NodeImportance/Component.tsx
- packages/gi-assets-algorithm/src/NodesSimilarity/Component.tsx
- packages/gi-assets-basic/src/components/PathAnalysis/Component.tsx
- packages/gi-common-components/src/NodeSelectionWrap/index.tsx
- packages/gi-common-components/src/index.ts
- packages/gi-sdk/src/process/loaderAssets.tsx
* 修复 js 资源加载失败时阻塞页面加载的问题
* 路径分析下方路径名与选择器保持一致
* 路径分析组件添加过滤选项
> 仅添加参数，组件复用时可用，用户不感知
* 节点重要性清理图标从“垃圾桶”调整为“扫帚”
> fix: 修复JS加载等若干小问题

- packages/gi-assets-basic/package.json
- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/components/RichContainer/index.less
> fix: add operator toolbar overlay

- packages/gi-site/src/services/initial.data/getConfigByEngineId.ts
🐛 Bugfix
- 修复模版使用SegmentedLayout布局时侧边栏默认填充组件
问题：创建模版时，如使用了 SegmentedLayout  布局，侧边栏默认填充组件
**before**
**after**
> fix(gi-site): 修复模版使用SegmentedLayout布局时侧边栏默认填充组件

- packages/gi-common-components/src/Icon/index.tsx
图标库里有的图标颜色被写死了，导致无法通过 css 设置颜色，如图
因此修正并替换了图标
> chore: update icons

- packages/gi-assets-basic/src/components/PinNodeWithMenu/Component.tsx
- packages/gi-assets-basic/src/components/common/handlePinNode.tsx
> feat: pin node with menu

- packages/gi-assets-neo4j/src/services/Driver.tsx
🐛 Bugfix
fix render problem caused by same id between nodes and edges
|![image](https://github.com/antvis/G6VP/assets/3632490/f41a0315-adde-4c19-993c-f112984240d6) | ![image](https://github.com/antvis/G6VP/assets/3632490/9f79f18a-91f6-4029-bc80-1fef17226988) |
https://github.com/antvis/G6VP/issues/555
> 🐛 Bugfix: fix render problem caused by same id between nodes and edges

- packages/gi-assets-algorithm/package.json
- packages/gi-assets-algorithm/src/PatternMatch/Component.tsx
> 之前的模式匹配导出模式数据有问题，导入数据也没做处理，因此无法导入导出模式
修复之后，导出的数据格式：
```json
{
"nodes": [
{
"id": "Tom",
"nodeType": "user",
"data": { "id": "Tom", "nodeType": "user" }
},
{
"id": "Gina",
"nodeType": "user",
"data": { "id": "Gina", "nodeType": "user" }
}
],
"edges": [
{
"id": "Tom-Gina-4",
"edgeType": "Friends_With",
"label": "Friends_With-0",
"source": "Tom",
"target": "Gina"
}
]
}
```
导入模式后进行匹配：
> fix: fix issue that cannot import pattern

- packages/gi-sdk-app/src/index.tsx
gi-sdk-app  支持 自定义 loading 
✨ Feature
🎨 Enhance
| ![image](https://github.com/antvis/G6VP/assets/103234654/cb0a90bf-312d-4544-90b6-4ab578e00e24)| 
|
> perf(gi-sdk-app): 支持自定义loading

- packages/gi-assets-basic/src/components/RichContainer/Component.tsx
- packages/gi-assets-basic/src/components/RichContainer/Toolbar.tsx
- packages/gi-common-components/src/CommonStyleSetting/IconPicker/index.tsx
✨ Feature
- [1 ] New feature
update flex container auto & tools icon styles update
🎨 Enhance
🐛 Bugfix
🔧 Chore
> feat: optimize component styles

- .github/workflows/auto-release.yml
- .github/workflows/lint.yml
- package.json
- packages/gi-common-components/src/Icon/index.tsx
- packages/gi-sdk-app/src/index.tsx
- packages/gi-sdk/src/GISDK.tsx
- packages/gi-sdk/src/hooks/useComponents.tsx
- packages/gi-sdk/src/typing.ts
- packages/gi-site/docker/website.Dockerfile
- packages/gi-site/package.json
🎨 Enhance
- [x ] Improve the performance
支持 GISDK 传入额外的 props 
额外props 格式约定为：
```tsx
interface GISDKProps {
/ ** 全局额外参数 */
GISDKExtraParams?: Record<string, any>;
/** 资产额外参数，以资产ID为 key, value 为传入对应资产的 props */
componentExtraParams?: Record<string, any>;
}
```
比如：
```tsx
const GISDKExtraParams = {
GI_AKG_AGENT_CONTEXT: {
id: 7,
agentCode: 'e690b81f43'
}
};
const componentExtraParams = {
// 传给 ToolBar 组件的 props
Toolbar: {
test: 123,
test2: 'abc'
}
}
```
使用在对应的资产中进行读取：
```
const context = useContext();
const { direction, components, assets, placement, offset, ...extraProps ...extraProps } = props;
console.log({
// 从 context 中读取存入全局的 extraParams
contextExtraProps: context.extraParams,
// 读取传给对应资产的 额外 props
componentExtraProps: extraProps
});
```
验证
> perf(GISDK): SDK 支持传入额外的 props
